const questionBank = {
    aptitude: {
        "Probability": [
            {q: "Two dice rolled, probability sum is 9?", opts: ["1/6", "1/9", "1/12", "1/18"], a: "1/9"},
            {q: "Probability of drawing ace or king from deck?", opts: ["1/13", "2/13", "4/13", "8/52"], a: "2/13"},
            {q: "Bag: 4 red, 6 blue. Probability both red without replacement?", opts: ["4/25", "2/15", "6/45", "8/90"], a: "2/15"},
            {q: "Three coins, probability exactly two heads?", opts: ["1/2", "1/4", "3/8", "5/8"], a: "3/8"},
            {q: "Probability of not getting 1 or 6 in dice roll?", opts: ["1/3", "2/3", "1/2", "5/6"], a: "2/3"},
            {q: "P(A)=0.6, P(B)=0.4, P(A∩B)=0.2, P(A∪B)=?", opts: ["0.6", "0.7", "0.8", "0.9"], a: "0.8"},
            {q: "Two cards drawn, probability both same suit?", opts: ["4/17", "12/51", "13/51", "1/4"], a: "12/51"},
            {q: "Probability of leap year having 53 Sundays?", opts: ["1/7", "2/7", "3/7", "4/7"], a: "2/7"},
            {q: "Bag: 3 green, 7 yellow. Probability different colors in two draws?", opts: ["7/15", "8/15", "1/2", "3/5"], a: "7/15"},
            {q: "Probability number divisible by 3 or 4 from 1-50?", opts: ["11/25", "23/50", "1/2", "12/25"], a: "23/50"},
            {q: "Probability of getting at least one head in 3 coin tosses?", opts: ["1/8", "3/8", "7/8", "5/8"], a: "7/8"},
            {q: "Bag: 5 red, 4 blue. Probability second ball red if first was red?", opts: ["4/9", "5/9", "1/2", "5/8"], a: "4/9"},
            {q: "Probability that randomly selected card is face card?", opts: ["3/13", "4/13", "1/4", "12/52"], a: "3/13"},
            {q: "Two events independent, P(A)=0.3, P(B)=0.4, P(A∩B)=?", opts: ["0.12", "0.7", "0.1", "0.58"], a: "0.12"},
            {q: "Probability of getting prime number when die is rolled?", opts: ["1/2", "1/3", "1/4", "2/3"], a: "1/2"},
            {q: "Three students probability of different birthdays?", opts: ["364/365", "363/365", "364/365²", "363/365²"], a: "364/365"},
            {q: "Bag: 8 white, 6 black. Probability both different colors?", opts: ["24/91", "48/91", "24/49", "12/49"], a: "48/91"},
            {q: "Probability of 53 Mondays in non-leap year?", opts: ["1/7", "2/7", "3/7", "4/7"], a: "1/7"},
            {q: "A can solve problem: 0.6, B: 0.7. Probability problem solved?", opts: ["0.88", "0.82", "0.78", "0.72"], a: "0.88"},
            {q: "Probability sum is 7 when two dice rolled?", opts: ["1/6", "1/9", "1/12", "5/36"], a: "1/6"},
            {q: "Cards drawn without replacement, probability both aces?", opts: ["1/221", "4/221", "3/221", "6/221"], a: "1/221"},
            {q: "Probability number between 1-100 divisible by 2 or 3?", opts: ["67/100", "17/25", "33/50", "3/5"], a: "67/100"},
            {q: "Bag: 3 red, 2 green. Probability at least one red in two draws?", opts: ["9/10", "3/5", "7/10", "4/5"], a: "9/10"},
            {q: "Probability of 5 Sundays in January?", opts: ["1/7", "2/7", "3/7", "4/7"], a: "3/7"},
            {q: "P(A)=1/3, P(B)=1/4, P(A∪B)=1/2, P(A∩B)=?", opts: ["1/12", "1/6", "1/4", "1/3"], a: "1/12"},
            {q: "Probability of drawing heart or king?", opts: ["4/13", "1/4", "17/52", "16/52"], a: "4/13"},
            {q: "Two dice, probability sum even or multiple of 3?", opts: ["2/3", "5/9", "7/12", "1/2"], a: "2/3"},
            {q: "Probability of 52 Sundays in leap year?", opts: ["5/7", "2/7", "3/7", "4/7"], a: "5/7"},
            {q: "Bag: 10 balls numbered 1-10. Probability prime or even?", opts: ["3/5", "7/10", "4/5", "3/4"], a: "3/5"},
            {q: "Probability of full house in poker?", opts: ["6/4165", "1/694", "3/2165", "1/500"], a: "6/4165"},
            {q: "Three coins, probability at most two heads?", opts: ["7/8", "3/4", "5/8", "1/2"], a: "7/8"},
            {q: "Probability random point in circle is closer to center than circumference?", opts: ["1/4", "1/2", "3/4", "1/3"], a: "1/4"},
            {q: "Two cards drawn with replacement, probability both spades?", opts: ["1/16", "3/52", "1/17", "12/52"], a: "1/16"},
            {q: "Probability product is even when two dice rolled?", opts: ["1/4", "1/2", "3/4", "5/6"], a: "3/4"},
            {q: "Bag: 4 red, 5 blue. Probability third ball red if first two unknown?", opts: ["4/9", "1/2", "5/9", "2/5"], a: "4/9"},
            {q: "Probability triangle formed with three random sticks of length 1-10?", opts: ["~0.5", "~0.25", "~0.75", "~0.9"], a: "~0.5"},
            {q: "Probability birthday match in 30 people?", opts: ["~0.7", "~0.5", "~0.3", "~0.9"], a: "~0.7"},
            {q: "Two events mutually exclusive, P(A)=0.4, P(B)=0.3, P(A∪B)=?", opts: ["0.7", "0.12", "0.58", "0.82"], a: "0.7"},
            {q: "Probability sum 8 when two dice rolled given first die shows 3?", opts: ["1/6", "1/3", "1/2", "2/3"], a: "1/6"},
            {q: "Probability random chord longer than side of equilateral triangle?", opts: ["1/3", "1/2", "2/3", "3/4"], a: "1/3"}
        ],
        "Percentages": [
            {q: "40% of 250 + 30% of 400 = ?", opts: ["200", "220", "240", "260"], a: "220"},
            {q: "If 25% of number is 75, the number is?", opts: ["250", "300", "200", "350"], a: "300"},
            {q: "Price increased 25%, then decreased 20%. Net change?", opts: ["No change", "5% increase", "5% decrease", "10% decrease"], a: "No change"},
            {q: "Population increases 20% annually. After 2 years from 5000?", opts: ["7000", "7200", "7500", "8000"], a: "7200"},
            {q: "Student scores 450/600. Percentage?", opts: ["70%", "75%", "80%", "85%"], a: "75%"},
            {q: "Salary increased from $3000 to $3600. Percentage increase?", opts: ["15%", "20%", "25%", "30%"], a: "20%"},
            {q: "After 15% discount, price $85. Original price?", opts: ["$95", "$100", "$90", "$85"], a: "$100"},
            {q: "If x is 20% more than y, y is what % less than x?", opts: ["16.67%", "20%", "25%", "30%"], a: "16.67%"},
            {q: "Product: 30% profit. If cost $140, selling price?", opts: ["$170", "$182", "$190", "$195"], a: "$182"},
            {q: "Number decreased by 40% gives 120. Original number?", opts: ["180", "200", "220", "240"], a: "200"},
            {q: "60% of 70 + 40% of 80 = ?", opts: ["74", "76", "78", "80"], a: "74"},
            {q: "If 15% of number is 45, 35% of same number?", opts: ["105", "115", "125", "135"], a: "105"},
            {q: "Price decreased 20% then increased 25%. Net change?", opts: ["No change", "5% increase", "5% decrease", "10% increase"], a: "No change"},
            {q: "Student gets 20% marks, fails by 30 marks. 32% marks, passes by 42 marks. Total marks?", opts: ["500", "600", "700", "800"], a: "600"},
            {q: "If A's income 25% more than B, B's income what % less than A?", opts: ["20%", "25%", "30%", "33.33%"], a: "20%"},
            {q: "Number increased by 20% gives 180. Original number?", opts: ["140", "150", "160", "170"], a: "150"},
            {q: "After 20% discount and 10% tax, price $88. Original price?", opts: ["$100", "$110", "$120", "$130"], a: "$100"},
            {q: "If 40% of number is 120, what is 120% of same number?", opts: ["300", "320", "340", "360"], a: "360"},
            {q: "Population decreases 10% annually. After 2 years from 10000?", opts: ["8100", "8200", "8300", "8400"], a: "8100"},
            {q: "Milk contains 5% water. Quantity of pure milk in 40L?", opts: ["38L", "38.5L", "39L", "39.5L"], a: "38L"},
            {q: "If 20% of (x+y) = 30% of (x-y), x:y?", opts: ["1:5", "5:1", "2:3", "3:2"], a: "5:1"},
            {q: "Salary increased 25% then decreased 20%. Net % change?", opts: ["0%", "5%", "10%", "15%"], a: "0%"},
            {q: "Student needs 40% to pass. Gets 120 marks, fails by 80 marks. Total marks?", opts: ["400", "500", "600", "700"], a: "500"},
            {q: "If 30% of number added to itself gives 390, the number is?", opts: ["280", "300", "320", "340"], a: "300"},
            {q: "Price increased 20%, consumption decreased 20%. Expenditure change?", opts: ["4% decrease", "4% increase", "No change", "2% decrease"], a: "4% decrease"},
            {q: "If 16% of number is 64, 64% of same number?", opts: ["256", "264", "272", "280"], a: "256"},
            {q: "After two successive discounts 10% and 20%, net discount?", opts: ["28%", "30%", "32%", "35%"], a: "28%"},
            {q: "If x is 25% less than y, y is what % more than x?", opts: ["25%", "33.33%", "50%", "75%"], a: "33.33%"},
            {q: "Number when increased by 15% becomes 230. Original number?", opts: ["195", "200", "205", "210"], a: "200"},
            {q: "If 5% of number is 25, 25% of same number?", opts: ["100", "125", "150", "175"], a: "125"},
            {q: "Price decreased 15% then increased 20%. Net % change?", opts: ["2% increase", "2% decrease", "No change", "5% increase"], a: "2% increase"},
            {q: "If 12% of number is 84, 84% of same number?", opts: ["588", "600", "612", "624"], a: "588"},
            {q: "Student gets 480/800. Percentage?", opts: ["55%", "58%", "60%", "62%"], a: "60%"},
            {q: "If A's salary 20% less than B, B's salary what % more than A?", opts: ["20%", "25%", "30%", "35%"], a: "25%"},
            {q: "After 25% discount, price $75. Original price?", opts: ["$90", "$95", "$100", "$105"], a: "$100"},
            {q: "Number decreased by 30% gives 210. Original number?", opts: ["280", "290", "300", "310"], a: "300"},
            {q: "If 45% of number is 180, 180% of same number?", opts: ["720", "740", "760", "780"], a: "720"},
            {q: "Price increased 10% then decreased 10%. Net change?", opts: ["1% decrease", "1% increase", "No change", "2% decrease"], a: "1% decrease"},
            {q: "If 8% of number is 72, 72% of same number?", opts: ["648", "656", "664", "672"], a: "648"},
            {q: "Population increases 15% annually. After 3 years from 8000?", opts: ["12167", "12200", "12300", "12400"], a: "12167"}
        ],
        "Time & Work": [
            {q: "A: 15 days, B: 20 days. Together?", opts: ["8 days", "60/7 days", "9 days", "10 days"], a: "60/7 days"},
            {q: "6 men complete work in 12 days. 8 men?", opts: ["7 days", "8 days", "9 days", "10 days"], a: "9 days"},
            {q: "A+B: 10 days, A: 15 days. B alone?", opts: ["20 days", "25 days", "30 days", "35 days"], a: "30 days"},
            {q: "3 men = 4 women. 6 men + 8 women in 20 days. 2 men + 3 women?", opts: ["28 days", "30 days", "32 days", "35 days"], a: "32 days"},
            {q: "Pipe A fills in 6 hrs, B empties in 8 hrs. Tank full, both open?", opts: ["20 hrs", "24 hrs", "28 hrs", "30 hrs"], a: "24 hrs"},
            {q: "A: 12 days, B: 18 days. A works 2 days, then B joins. Total?", opts: ["6.5 days", "7.2 days", "8 days", "9 days"], a: "7.2 days"},
            {q: "6 workers in 15 days. After 5 days, 3 left. Total days?", opts: ["20 days", "25 days", "28 days", "30 days"], a: "25 days"},
            {q: "A+B: 8 days, B+C: 10 days, A+C: 12 days. All three?", opts: ["100/17 days", "120/17 days", "130/17 days", "140/17 days"], a: "120/17 days"},
            {q: "Man doubles efficiency daily. Completes in 6 days. Normal days?", opts: ["10 days", "12 days", "14 days", "16 days"], a: "12 days"},
            {q: "Women: 6 in 10 days or 10 in 8 days. 12 women?", opts: ["3 days", "4 days", "5 days", "6 days"], a: "4 days"},
            {q: "A: 20 days, B: 30 days. Both work for 5 days, then A leaves. Remaining work by B?", opts: ["15 days", "17.5 days", "20 days", "22.5 days"], a: "17.5 days"},
            {q: "15 men complete work in 30 days. After 10 days, 5 more join. Total days?", opts: ["25 days", "26 days", "27 days", "28 days"], a: "27 days"},
            {q: "A+B+C complete work in 10 days. A+B in 12 days, B+C in 15 days. A alone?", opts: ["20 days", "24 days", "30 days", "36 days"], a: "30 days"},
            {q: "8 children complete work in 24 days. 12 women in 16 days. 8 children + 6 women?", opts: ["9.6 days", "10 days", "11.2 days", "12 days"], a: "9.6 days"},
            {q: "Pipe A fills in 10 hrs, B in 15 hrs, C empties in 12 hrs. All open, empty tank fills in?", opts: ["15 hrs", "18 hrs", "20 hrs", "24 hrs"], a: "20 hrs"},
            {q: "A is twice as efficient as B. Together in 14 days. B alone?", opts: ["21 days", "28 days", "35 days", "42 days"], a: "42 days"},
            {q: "Work completed by 12 men in 18 days. Same work by 8 women in 27 days. 6 men + 4 women?", opts: ["16 days", "18 days", "20 days", "22 days"], a: "18 days"},
            {q: "A completes 60% work in 15 days. Then B joins, complete in 5 more days. B alone?", opts: ["25 days", "30 days", "35 days", "40 days"], a: "25 days"},
            {q: "20 men complete work in 15 days working 8 hrs/day. 25 men working 6 hrs/day?", opts: ["16 days", "18 days", "20 days", "22 days"], a: "16 days"},
            {q: "A+B: 12 days, B+C: 15 days, C+A: 20 days. A alone?", opts: ["20 days", "24 days", "30 days", "36 days"], a: "30 days"},
            {q: "15 workers in 20 days. After 8 days, 5 workers left. 4 days later, 10 more joined. Total days?", opts: ["18 days", "20 days", "22 days", "24 days"], a: "22 days"},
            {q: "A can do work in 24 days, B in 32 days. With help of C, complete in 12 days. C alone?", opts: ["36 days", "40 days", "48 days", "56 days"], a: "48 days"},
            {q: "30 men working 9 hrs/day complete work in 16 days. 36 men working 8 hrs/day?", opts: ["12 days", "15 days", "18 days", "20 days"], a: "15 days"},
            {q: "A+B: 20 days, A alone: 30 days. After both work for 10 days, A leaves. B completes remaining in?", opts: ["5 days", "10 days", "15 days", "20 days"], a: "5 days"},
            {q: "12 pumps working 8 hrs/day empty reservoir in 20 days. 16 pumps working 6 hrs/day?", opts: ["18 days", "20 days", "22 days", "24 days"], a: "20 days"},
            {q: "A completes work in 18 days, B in 24 days. A works for 6 days then B joins. Total days?", opts: ["10 days", "12 days", "14 days", "16 days"], a: "12 days"},
            {q: "45 men complete work in 30 days. After 20 days, 15 left. Remaining work completed in?", opts: ["15 days", "18 days", "20 days", "25 days"], a: "15 days"},
            {q: "A is 50% more efficient than B. Together complete in 12 days. B alone?", opts: ["18 days", "20 days", "24 days", "30 days"], a: "30 days"},
            {q: "24 women complete work in 16 days. 16 men in 24 days. 12 women + 8 men?", opts: ["16 days", "18 days", "20 days", "22 days"], a: "16 days"},
            {q: "A+B: 15 days, B+C: 20 days, C+A: 25 days. All three together?", opts: ["300/37 days", "300/31 days", "300/29 days", "300/27 days"], a: "300/37 days"},
            {q: "Work completed by 25 men in 20 days. Same by 20 women in 30 days. 10 men + 15 women?", opts: ["20 days", "24 days", "28 days", "30 days"], a: "24 days"},
            {q: "A completes 1/3 work in 10 days. Then B joins, complete remaining in 15 days. B alone?", opts: ["30 days", "36 days", "40 days", "45 days"], a: "36 days"},
            {q: "18 men complete work in 24 days working 7 hrs/day. 21 men working 8 hrs/day?", opts: ["12 days", "14 days", "15 days", "16 days"], a: "15 days"},
            {q: "A+B: 18 days, A+C: 24 days, B+C: 36 days. C alone?", opts: ["48 days", "54 days", "60 days", "72 days"], a: "72 days"},
            {q: "30 workers complete work in 25 days. After 15 days, 10 workers left. 5 days later, 20 more joined. Total days?", opts: ["28 days", "30 days", "32 days", "35 days"], a: "28 days"},
            {q: "A can do work in 40 days, B in 60 days. With help of C, complete in 15 days. Share of C if total ₹6000?", opts: ["₹1500", "₹2000", "₹2500", "₹3000"], a: "₹2500"},
            {q: "24 men working 10 hrs/day complete work in 18 days. 30 men working 8 hrs/day?", opts: ["16 days", "18 days", "20 days", "22 days"], a: "18 days"},
            {q: "A+B: 25 days, B alone: 40 days. After both work for 15 days, A leaves. B completes remaining in?", opts: ["10 days", "12 days", "14 days", "16 days"], a: "10 days"},
            {q: "16 pumps working 9 hrs/day empty reservoir in 15 days. 20 pumps working 6 hrs/day?", opts: ["16 days", "18 days", "20 days", "22 days"], a: "18 days"},
            {q: "A+B+C complete work in 8 days. A+B in 12 days, B+C in 16 days. C alone?", opts: ["24 days", "28 days", "32 days", "36 days"], a: "48 days"}
        ],
        "Profit & Loss": [
            {q: "Cost $120, sold $150. Profit %?", opts: ["20%", "25%", "30%", "35%"], a: "25%"},
            {q: "Sold at 20% profit for $180. Cost price?", opts: ["$140", "$150", "$160", "$170"], a: "$150"},
            {q: "Two successive discounts 20% and 10%. Net discount?", opts: ["25%", "28%", "30%", "32%"], a: "28%"},
            {q: "Marked price $200, discount 15%. Selling price?", opts: ["$160", "$170", "$180", "$190"], a: "$170"},
            {q: "Cost $80, sold at 25% loss. Selling price?", opts: ["$55", "$60", "$65", "$70"], a: "$60"},
            {q: "If 20% loss, selling price $160. Cost price?", opts: ["$180", "$190", "$200", "$210"], a: "$200"},
            {q: "Item sold at 30% profit. If cost $70 more, 10% loss. Cost?", opts: ["$40", "$50", "$60", "$70"], a: "$50"},
            {q: "Bought 20 items at $15 each, sold at $18 each. Profit %?", opts: ["15%", "18%", "20%", "25%"], a: "20%"},
            {q: "Sold two items each at $990. One 10% profit, one 10% loss. Net?", opts: ["1% profit", "1% loss", "No profit no loss", "2% loss"], a: "1% loss"},
            {q: "Markup 40% on cost, discount 20% on marked. Net profit %?", opts: ["10%", "12%", "15%", "18%"], a: "12%"},
            {q: "Cost price $240, sold at 25% profit. Selling price?", opts: ["$280", "$290", "$300", "$310"], a: "$300"},
            {q: "Sold at 15% loss for $340. Cost price?", opts: ["$380", "$390", "$400", "$410"], a: "$400"},
            {q: "Three successive discounts 10%, 20%, 25%. Net discount?", opts: ["46%", "48%", "50%", "52%"], a: "46%"},
            {q: "Marked price $500, two discounts 20% and 10%. Selling price?", opts: ["$340", "$350", "$360", "$370"], a: "$360"},
            {q: "Cost $150, wants 20% profit after 10% discount. Marked price?", opts: ["$190", "$200", "$210", "$220"], a: "$200"},
            {q: "Bought 50 items at $12 each, sold 30 at $15 each, rest at $10 each. Profit/loss %?", opts: ["2.5% profit", "2.5% loss", "No profit no loss", "5% profit"], a: "2.5% profit"},
            {q: "If selling price doubled, profit triples. Profit %?", opts: ["50%", "100%", "150%", "200%"], a: "100%"},
            {q: "Cost price of 20 articles = selling price of 16 articles. Profit %?", opts: ["20%", "25%", "30%", "35%"], a: "25%"},
            {q: "Sold at 20% profit. If cost price was 10% less and selling price $10 less, profit 25%. Original cost?", opts: ["$40", "$50", "$60", "$70"], a: "$50"},
            {q: "Marked price 25% above cost. After discount, profit 12.5%. Discount %?", opts: ["10%", "12%", "15%", "18%"], a: "10%"},
            {q: "Bought two items $600 each. Sold one at 10% profit, other at 10% loss. Net?", opts: ["No profit no loss", "1% loss", "2% loss", "1% profit"], a: "No profit no loss"},
            {q: "Cost $400, marked 50% above cost. After discount, profit 20%. Discount %?", opts: ["15%", "18%", "20%", "22%"], a: "20%"},
            {q: "Sold 2 items each at $2160. One 20% profit, one 20% loss. Net?", opts: ["4% loss", "4% profit", "No profit no loss", "2% loss"], a: "4% loss"},
            {q: "Cost price of 25 articles = selling price of 20 articles. Profit %?", opts: ["20%", "25%", "30%", "35%"], a: "25%"},
            {q: "After two discounts 15% and 10%, selling price $765. Marked price?", opts: ["$980", "$1000", "$1020", "$1040"], a: "$1000"},
            {q: "Bought 100 shares at $50 each. Sold 60 at $60 each, rest at $45 each. Net profit/loss?", opts: ["$300 profit", "$300 loss", "$400 profit", "$400 loss"], a: "$300 profit"},
            {q: "If 10% discount, profit 20%. If 20% discount, profit?", opts: ["5%", "6.67%", "7.5%", "8%"], a: "6.67%"},
            {q: "Cost $500, sold at 25% profit. If sold at 20% profit, difference?", opts: ["$20", "$25", "$30", "$35"], a: "$25"},
            {q: "Marked price 30% above cost. After 10% discount, profit %?", opts: ["15%", "17%", "18%", "20%"], a: "17%"},
            {q: "Bought 80 items at $25 each. Sold 50 at $30 each, 30 at $28 each. Profit %?", opts: ["12.4%", "13.6%", "14.8%", "15.2%"], a: "13.6%"},
            {q: "If selling price of 10 articles = cost price of 11 articles. Profit %?", opts: ["10%", "11%", "12%", "13%"], a: "10%"},
            {q: "Cost $600, wants 25% profit after 15% discount. Marked price?", opts: ["$850", "$880", "$900", "$920"], a: "$880"},
            {q: "Sold at 15% profit. If cost was 5% less and sold at same price, profit %?", opts: ["20%", "21.05%", "22%", "23%"], a: "21.05%"},
            {q: "Three successive discounts 20%, 10%, 5%. Net discount?", opts: ["31.6%", "32.4%", "33.2%", "34%"], a: "31.6%"},
            {q: "Cost $800, marked 40% above cost. After discount, profit 12%. Discount %?", opts: ["18%", "20%", "22%", "25%"], a: "20%"},
            {q: "Bought 120 articles at $2.50 each. Sold 80 at $3 each, rest at $2 each. Profit %?", opts: ["8%", "10%", "12%", "15%"], a: "8%"},
            {q: "If 15% profit, selling price $460. Cost price?", opts: ["$390", "$400", "$410", "$420"], a: "$400"},
            {q: "Marked price $750, discount 12%. Selling price?", opts: ["$650", "$660", "$670", "$680"], a: "$660"},
            {q: "Cost $350, sold at 18% profit. Selling price?", opts: ["$405", "$410", "$413", "$420"], a: "$413"},
            {q: "Bought two items $800 each. Sold one at 15% profit, other at 15% loss. Net?", opts: ["2.25% loss", "No profit no loss", "1.5% loss", "2% loss"], a: "2.25% loss"}
        ],
        "Ages": [
            {q: "Father 40, son 10. After how many years father twice?", opts: ["15 years", "18 years", "20 years", "22 years"], a: "20 years"},
            {q: "A:B age ratio 3:5. After 10 years 2:3. Current A?", opts: ["25 years", "28 years", "30 years", "32 years"], a: "30 years"},
            {q: "Sum of ages father+son=50. 5 years ago ratio 7:1. Son now?", opts: ["8 years", "10 years", "12 years", "14 years"], a: "10 years"},
            {q: "Mother 4 times daughter. After 5 years 3 times. Daughter now?", opts: ["8 years", "10 years", "12 years", "15 years"], a: "10 years"},
            {q: "A+B=60, A=B+10. A's age?", opts: ["32 years", "35 years", "38 years", "40 years"], a: "35 years"},
            {q: "Ratio 4:3. After 6 years 5:4. Current ages?", opts: ["20,15", "22,16", "24,18", "26,20"], a: "24,18"},
            {q: "10 years ago A was thrice B. Now twice. B's age?", opts: ["18 years", "20 years", "22 years", "24 years"], a: "20 years"},
            {q: "Father 50, sons 20 and 15. When sum sons = father?", opts: ["12 years", "15 years", "18 years", "20 years"], a: "15 years"},
            {q: "A is 2 years older than B. Ratio ages after 3 years 5:4. B now?", opts: ["3 years", "5 years", "7 years", "9 years"], a: "5 years"},
            {q: "Average age family 4 members 25. If father excluded, 20. Father?", opts: ["35 years", "38 years", "40 years", "42 years"], a: "40 years"},
            {q: "Present ages A:B=5:4. After 3 years, ratio 11:9. A's present age?", opts: ["25 years", "28 years", "30 years", "32 years"], a: "30 years"},
            {q: "Sum ages father+mother+son=96. Father twice son, mother=father+son. Son's age?", opts: ["16 years", "18 years", "20 years", "22 years"], a: "16 years"},
            {q: "5 years ago, A was thrice B. 10 years later, A twice B. B's present age?", opts: ["18 years", "20 years", "22 years", "24 years"], a: "20 years"},
            {q: "Ratio ages A:B=2:3, B:C=4:5. Sum A+B+C=98. C's age?", opts: ["30 years", "35 years", "40 years", "45 years"], a: "40 years"},
            {q: "Father 45, son 15. After how many years father thrice son?", opts: ["5 years", "0 years", "10 years", "15 years"], a: "0 years"},
            {q: "A+B=60 years. A says 'I am twice as old as B when I was his age'. Their ages?", opts: ["36,24", "35,25", "40,20", "45,15"], a: "36,24"},
            {q: "Present age ratio 4:5. After 18 years, ratio 11:13. Present ages?", opts: ["24,30", "28,35", "32,40", "36,45"], a: "24,30"},
            {q: "Sum ages couple 10 years ago=52. Now husband older by 4 years. Husband's age?", opts: ["33 years", "35 years", "37 years", "39 years"], a: "37 years"},
            {q: "A is 4 years older than B. After 16 years, A twice as old as B 6 years ago. B's present age?", opts: ["12 years", "14 years", "16 years", "18 years"], a: "14 years"},
            {q: "Average age 30 students=15 years. Teacher 45 years included. New average?", opts: ["15.5 years", "16 years", "16.5 years", "17 years"], a: "16 years"},
            {q: "Present age ratio A:B=3:4. After 5 years, B's age=25. A's present age?", opts: ["12 years", "15 years", "18 years", "20 years"], a: "15 years"},
            {q: "Sum ages parents=70. 10 years ago ratio=5:4. Father's age?", opts: ["35 years", "38 years", "40 years", "42 years"], a: "40 years"},
            {q: "A+B=50 years. 5 years ago A was 3 times B. A's age?", opts: ["32 years", "35 years", "38 years", "40 years"], a: "35 years"},
            {q: "Ratio ages 3:4:5. Sum=96. Age of youngest?", opts: ["20 years", "22 years", "24 years", "26 years"], a: "24 years"},
            {q: "Father 45, son 20. Before how many years father 4 times son?", opts: ["5 years", "8 years", "10 years", "12 years"], a: "5 years"},
            {q: "A is 15 years older than B. After 5 years, A twice B. B's present age?", opts: ["8 years", "10 years", "12 years", "14 years"], a: "10 years"},
            {q: "Present age ratio 7:9. After 10 years, ratio 11:13. Younger's age?", opts: ["25 years", "28 years", "30 years", "35 years"], a: "35 years"},
            {q: "Sum ages family 4 members=120. 5 years ago=100. How many members?", opts: ["4", "5", "6", "7"], a: "4"},
            {q: "A+B=65 years. A is 5 years younger than B. B's age?", opts: ["30 years", "32 years", "34 years", "35 years"], a: "35 years"},
            {q: "Ratio ages 2:3:4. After 5 years, sum=75. Present ages?", opts: ["14,21,28", "15,22,29", "16,24,32", "18,27,36"], a: "16,24,32"},
            {q: "Father 50, son 24. After how many years father twice son?", opts: ["1 year", "2 years", "3 years", "4 years"], a: "2 years"},
            {q: "A+B=60. A says 'I am twice as old as B when I was his age'. A's age?", opts: ["32 years", "35 years", "38 years", "40 years"], a: "40 years"},
            {q: "Present age ratio 3:5. After 9 years, ratio 3:4. Present ages?", opts: ["24,40", "27,45", "30,50", "33,55"], a: "27,45"},
            {q: "Sum ages couple=85. Husband older by 5 years. Wife's age?", opts: ["38 years", "40 years", "42 years", "45 years"], a: "40 years"},
            {q: "A is 8 years older than B. After 12 years, A twice as old as B 4 years ago. A's present age?", opts: ["24 years", "26 years", "28 years", "30 years"], a: "28 years"},
            {q: "Average age 25 students=14 years. Teacher 40 years included. New average?", opts: ["14.5 years", "15 years", "15.5 years", "16 years"], a: "15 years"},
            {q: "Present age ratio A:B=5:6. After 7 years, B's age=31. A's present age?", opts: ["18 years", "20 years", "22 years", "24 years"], a: "20 years"},
            {q: "Sum ages parents=80. 15 years ago ratio=7:5. Mother's age?", opts: ["35 years", "38 years", "40 years", "42 years"], a: "35 years"},
            {q: "A+B=55 years. 8 years ago A was 3 times B. B's age?", opts: ["15 years", "18 years", "20 years", "22 years"], a: "18 years"},
            {q: "Ratio ages 4:5:6. Sum=105. Age of oldest?", opts: ["30 years", "35 years", "40 years", "42 years"], a: "42 years"}
        ],
        "Averages": [
            {q: "Average of 5, 10, 15, 20, 25?", opts: ["15", "16", "17", "18"], a: "15"},
            {q: "Average of first 20 natural numbers?", opts: ["10.5", "11", "11.5", "12"], a: "10.5"},
            {q: "Average weight of 5 people 60kg. If one 70kg joins, new average?", opts: ["61kg", "62kg", "63kg", "64kg"], a: "61kg"},
            {q: "Student scores 85, 90, 78 in three tests. Average needed in 4th for 85 overall?", opts: ["85", "87", "88", "90"], a: "87"},
            {q: "Average of 11 numbers 30. If first 6 average 28, last 6 average 32, 6th number?", opts: ["28", "30", "32", "34"], a: "30"},
            {q: "Average salary 10 employees $5000. Manager salary $15000. Company average?", opts: ["$5500", "$6000", "$6363", "$6500"], a: "$6363"},
            {q: "Average of 7 numbers 18. If each number multiplied by 3, new average?", opts: ["18", "36", "54", "72"], a: "54"},
            {q: "Average age 20 students 15 years. Teacher 35 years included, new average?", opts: ["15.5", "16", "16.5", "17"], a: "16"},
            {q: "Average of 15 numbers 25. If 5 is subtracted from each, new average?", opts: ["20", "22", "23", "25"], a: "20"},
            {q: "Average runs 10 innings 40. In 11th innings, scored 100 runs. New average?", opts: ["42", "44", "46", "48"], a: "44"},
            {q: "Average of 8 numbers 15. If each number increased by 5, new average?", opts: ["18", "20", "22", "25"], a: "20"},
            {q: "Average weight 8 persons 60kg. Two persons 55kg each leave. New average?", opts: ["61kg", "62kg", "63kg", "64kg"], a: "61kg"},
            {q: "Average of 25 numbers 40. If 5 is added to each number, new average?", opts: ["40", "42", "45", "48"], a: "45"},
            {q: "Student scores 60, 70, 80 in three subjects. Average needed in 4th for 75 overall?", opts: ["80", "85", "90", "95"], a: "90"},
            {q: "Average of 12 numbers 24. If each number divided by 3, new average?", opts: ["6", "8", "10", "12"], a: "8"},
            {q: "Average age family 6 members 25 years. Youngest child 5 years excluded. New average?", opts: ["28 years", "29 years", "30 years", "31 years"], a: "29 years"},
            {q: "Average of 9 numbers 50. If first 5 average 45, last 5 average 55, 5th number?", opts: ["45", "50", "55", "60"], a: "50"},
            {q: "Average marks 30 students 45. 5 students with average 60 join. New average?", opts: ["46.4", "47.1", "48.2", "49.5"], a: "46.4"},
            {q: "Average of 6 numbers 18. If 3 is added to first three numbers, new average?", opts: ["19", "19.5", "20", "20.5"], a: "19.5"},
            {q: "Average salary 20 employees $4000. 5 employees with average $6000 join. New average?", opts: ["$4200", "$4300", "$4400", "$4500"], a: "$4300"},
            {q: "Average of 10 numbers 35. If each number multiplied by 2 and then 5 added, new average?", opts: ["70", "72", "75", "78"], a: "75"},
            {q: "Average weight 12 boys 40kg. 3 boys with average 45kg leave. New average?", opts: ["38.5kg", "39kg", "39.5kg", "40kg"], a: "39kg"},
            {q: "Average of 7 numbers 24. If mean of first 3 is 20, last 3 is 26, 4th number?", opts: ["24", "26", "28", "30"], a: "30"},
            {q: "Student needs 40% to pass. Gets 50, 60, 70 in three tests out of 100 each. Minimum in 4th test?", opts: ["20", "25", "30", "35"], a: "20"},
            {q: "Average of 15 observations 32. Later found 23 was misread as 32. Correct average?", opts: ["31", "31.4", "31.6", "32"], a: "31.4"},
            {q: "Average temperature Monday to Thursday 38°C. Tuesday to Friday 40°C. Friday 41°C. Monday?", opts: ["35°C", "36°C", "37°C", "38°C"], a: "35°C"},
            {q: "Average of 8 numbers 12. If each number increased by 25%, new average?", opts: ["14", "15", "16", "18"], a: "15"},
            {q: "Average weight 10 persons 50kg. 2 persons 60kg each join. New average?", opts: ["51kg", "52kg", "53kg", "54kg"], a: "52kg"},
            {q: "Average of 20 numbers 45. If 5 is subtracted from each number, new average?", opts: ["40", "42", "44", "45"], a: "40"},
            {q: "Student scores 65, 75, 85 in three tests. Average needed in 4th for 80 overall?", opts: ["85", "90", "95", "100"], a: "95"},
            {q: "Average of 6 numbers 22. If each number divided by 2, new average?", opts: ["10", "11", "12", "13"], a: "11"},
            {q: "Average age 25 students 16 years. Teacher 40 years included. New average?", opts: ["16.5 years", "17 years", "17.5 years", "18 years"], a: "17 years"},
            {q: "Average of 9 numbers 30. If first 4 average 25, last 4 average 35, 5th number?", opts: ["25", "30", "35", "40"], a: "30"},
            {q: "Average marks 40 students 60. 10 students with average 80 join. New average?", opts: ["62", "64", "66", "68"], a: "64"},
            {q: "Average of 7 numbers 20. If 4 is added to first four numbers, new average?", opts: ["21", "21.7", "22", "22.3"], a: "21.7"},
            {q: "Average salary 30 employees $3000. 10 employees with average $5000 join. New average?", opts: ["$3200", "$3400", "$3500", "$3600"], a: "$3500"},
            {q: "Average of 12 numbers 48. If each number multiplied by 1.5, new average?", opts: ["60", "64", "68", "72"], a: "72"},
            {q: "Average weight 15 persons 55kg. 5 persons with average 65kg leave. New average?", opts: ["52kg", "53kg", "54kg", "55kg"], a: "52kg"},
            {q: "Average of 8 numbers 16. If mean of first 4 is 14, last 4 is 18, what is true?", opts: ["All equal", "4th=5th", "Cannot determine", "Average correct"], a: "Average correct"},
            {q: "Student needs 35% to pass. Gets 40, 50, 30 in three tests out of 100 each. Minimum in 4th test?", opts: ["10", "15", "20", "25"], a: "20"}
        ],
        "Ratios": [
            {q: "If a:b=3:4 and b:c=6:5, find a:b:c?", opts: ["3:4:5", "9:12:10", "6:8:5", "3:6:5"], a: "9:12:10"},
            {q: "Divide 600 in ratio 2:3:5", opts: ["120,180,300", "100,200,300", "150,200,250", "200,200,200"], a: "120,180,300"},
            {q: "If x:y=3:4 and y:z=2:3, find x:z?", opts: ["1:2", "3:2", "2:3", "1:3"], a: "1:2"},
            {q: "Ratio boys:girls=3:2. If 60 boys, how many girls?", opts: ["30", "40", "50", "60"], a: "40"},
            {q: "Two numbers ratio 5:7. Their sum 180. Find numbers?", opts: ["75,105", "80,100", "70,110", "65,115"], a: "75,105"},
            {q: "If 2A=3B=4C, find A:B:C?", opts: ["2:3:4", "6:4:3", "3:4:6", "4:3:2"], a: "6:4:3"},
            {q: "Ratio 5:3. If difference 24, find larger number?", opts: ["48", "56", "60", "72"], a: "60"},
            {q: "Income ratio 4:5, expenditure ratio 7:9. Savings equal. Find incomes?", opts: ["4000,5000", "4800,6000", "5200,6500", "5600,7000"], a: "4800,6000"},
            {q: "Ratio 3:4 becomes 4:5 when 5 added to both. Original numbers?", opts: ["12,16", "15,20", "18,24", "21,28"], a: "15,20"},
            {q: "Mixture milk:water=4:1. If 10L water added, ratio becomes 4:3. Original milk?", opts: ["20L", "25L", "30L", "35L"], a: "20L"},
            {q: "If a:b=2:3, b:c=4:5, c:d=6:7, find a:b:c:d?", opts: ["16:24:30:35", "8:12:15:17.5", "16:24:30:42", "8:12:15:21"], a: "16:24:30:35"},
            {q: "Divide 391 in ratio 1/2:2/3:3/4", opts: ["102,136,153", "100,135,156", "105,140,146", "110,145,136"], a: "102,136,153"},
            {q: "Ratio 7:8. If each number increased by 10, ratio becomes 8:9. Original numbers?", opts: ["70,80", "63,72", "77,88", "84,96"], a: "70,80"},
            {q: "If (x+y):(x-y)=5:2, find x:y?", opts: ["7:3", "5:2", "3:1", "4:1"], a: "7:3"},
            {q: "Number of students 3:2. If 20 more boys, ratio becomes 7:5. Original boys?", opts: ["60", "80", "100", "120"], a: "60"},
            {q: "Ratio copper:zinc=5:3. If 16kg zinc added, ratio becomes 5:4. Original copper?", opts: ["40kg", "50kg", "60kg", "70kg"], a: "40kg"},
            {q: "If A:B=2:3, B:C=4:5, C:D=6:7, find A:D?", opts: ["16:35", "8:35", "16:105", "8:105"], a: "16:35"},
            {q: "Two numbers ratio 3:5. If each increased by 10, ratio becomes 5:7. Numbers?", opts: ["15,25", "18,30", "21,35", "24,40"], a: "15,25"},
            {q: "Income A:B=3:4, expenditure A:B=4:5. Savings A=1/4 income. B's savings?", opts: ["1/2 income", "1/3 income", "1/4 income", "1/5 income"], a: "1/4 income"},
            {q: "Ratio boys:girls=4:5. If 100 girls added, ratio becomes 6:7. Original students?", opts: ["540", "600", "660", "720"], a: "540"},
            {q: "If 2A=3B and 4B=5C, find A:C?", opts: ["8:15", "15:8", "5:6", "6:5"], a: "15:8"},
            {q: "Divide 1250 in ratio 2:3:5", opts: ["250,375,625", "200,400,650", "300,350,600", "275,375,600"], a: "250,375,625"},
            {q: "Ratio 5:6. If each decreased by 8, ratio becomes 4:5. Original numbers?", opts: ["40,48", "45,54", "50,60", "55,66"], a: "40,48"},
            {q: "If (2x+3y):(3x+5y)=18:29, find x:y?", opts: ["1:2", "2:3", "3:4", "4:5"], a: "3:4"},
            {q: "Students boys:girls=7:8. If 20 girls leave, ratio becomes 8:7. Original girls?", opts: ["80", "96", "112", "128"], a: "96"},
            {q: "Alloy A:B=3:4. If 28kg B added, ratio becomes 3:5. Original alloy?", opts: ["84kg", "96kg", "108kg", "120kg"], a: "84kg"},
            {q: "If A:B=3:4, B:C=5:6, C:D=7:8, find A:B:C:D?", opts: ["105:140:168:192", "35:56:72:96", "70:84:96:112", "45:60:72:84"], a: "105:140:168:192"},
            {q: "Two numbers ratio 4:7. If each decreased by 4, ratio becomes 3:5. Numbers?", opts: ["16,28", "20,35", "24,42", "28,49"], a: "16,28"},
            {q: "Income X:Y=5:4, expenditure X:Y=3:2. Savings X=2000, Y=3000. X's income?", opts: ["10000", "12000", "15000", "18000"], a: "15000"},
            {q: "Ratio men:women=5:4. If 45 women added, ratio becomes 5:6. Original people?", opts: ["180", "225", "270", "315"], a: "225"},
            {q: "If 3A=4B and 5B=6C, find A:B:C?", opts: ["20:15:18", "15:12:10", "20:15:12", "12:9:10"], a: "20:15:18"},
            {q: "Divide 216 in ratio 1/3:1/4:1/6", opts: ["96,72,48", "90,75,51", "100,70,46", "104,68,44"], a: "96,72,48"},
            {q: "Ratio 8:9. If each increased by 5, ratio becomes 9:10. Original numbers?", opts: ["40,45", "48,54", "56,63", "64,72"], a: "40,45"},
            {q: "If (3x+4y):(4x+3y)=5:6, find x:y?", opts: ["2:3", "3:4", "4:5", "5:6"], a: "2:3"},
            {q: "Students science:arts=5:6. If 30 science added, ratio becomes 7:6. Original arts?", opts: ["120", "144", "168", "192"], a: "144"},
            {q: "Mixture sugar:flour=2:5. If 9kg flour added, ratio becomes 1:3. Original sugar?", opts: ["6kg", "8kg", "10kg", "12kg"], a: "6kg"},
            {q: "If A:B=2:3, B:C=4:9, C:D=3:5, find A:B:C:D?", opts: ["8:12:27:45", "16:24:54:90", "4:6:9:15", "2:3:9:15"], a: "8:12:27:45"},
            {q: "Two numbers ratio 5:8. If each increased by 12, ratio becomes 7:10. Numbers?", opts: ["25,40", "30,48", "35,56", "40,64"], a: "30,48"},
            {q: "Income P:Q=7:5, expenditure P:Q=3:2. Savings P=4000, Q=5000. Q's income?", opts: ["10000", "12500", "15000", "17500"], a: "12500"},
            {q: "Ratio children:adults=3:7. If 35 adults added, ratio becomes 1:3. Original adults?", opts: ["105", "140", "175", "210"], a: "105"}
        ],
        "Series": [
            {q: "Next number: 2, 6, 12, 20, 30, ?", opts: ["40", "42", "44", "46"], a: "42"},
            {q: "Next number: 1, 4, 9, 16, 25, ?", opts: ["36", "38", "40", "42"], a: "36"},
            {q: "Next number: 1, 3, 6, 10, 15, ?", opts: ["20", "21", "22", "23"], a: "21"},
            {q: "Next number: 2, 4, 8, 16, 32, ?", opts: ["48", "56", "64", "72"], a: "64"},
            {q: "Next number: 1, 1, 2, 3, 5, 8, ?", opts: ["11", "12", "13", "14"], a: "13"},
            {q: "Missing number: 5, 11, 23, 47, ?", opts: ["85", "89", "95", "97"], a: "95"},
            {q: "Next number: 3, 9, 27, 81, ?", opts: ["243", "244", "245", "246"], a: "243"},
            {q: "Missing number: 2, 5, 10, 17, 26, ?", opts: ["35", "36", "37", "38"], a: "37"},
            {q: "Next number: 1, 8, 27, 64, ?", opts: ["100", "110", "120", "125"], a: "125"},
            {q: "Missing number: 1, 4, 27, 256, ?", opts: ["3125", "3245", "3355", "3456"], a: "3125"},
            {q: "Next number: 0, 1, 1, 2, 3, 5, 8, 13, ?", opts: ["18", "20", "21", "22"], a: "21"},
            {q: "Missing number: 2, 6, 18, 54, ?", opts: ["108", "126", "162", "216"], a: "162"},
            {q: "Next number: 1, 4, 9, 16, 25, 36, ?", opts: ["49", "56", "64", "72"], a: "49"},
            {q: "Missing number: 3, 7, 15, 31, ?", opts: ["47", "53", "63", "65"], a: "63"},
            {q: "Next number: 1, 3, 7, 15, 31, ?", opts: ["47", "53", "63", "65"], a: "63"},
            {q: "Missing number: 2, 3, 5, 7, 11, ?", opts: ["13", "15", "17", "19"], a: "13"},
            {q: "Next number: 1, 2, 4, 8, 16, ?", opts: ["24", "28", "32", "36"], a: "32"},
            {q: "Missing number: 1, 8, 27, 64, 125, ?", opts: ["196", "216", "225", "256"], a: "216"},
            {q: "Next number: 2, 5, 10, 17, 26, 37, ?", opts: ["48", "50", "52", "54"], a: "50"},
            {q: "Missing number: 1, 1, 2, 3, 5, 8, 13, ?", opts: ["18", "20", "21", "22"], a: "21"},
            {q: "Next number: 3, 6, 11, 18, 27, ?", opts: ["36", "38", "40", "42"], a: "38"},
            {q: "Missing number: 2, 4, 12, 48, ?", opts: ["96", "144", "192", "240"], a: "240"},
            {q: "Next number: 1, 4, 10, 22, 46, ?", opts: ["64", "82", "94", "100"], a: "94"},
            {q: "Missing number: 1, 3, 9, 27, 81, ?", opts: ["108", "135", "162", "243"], a: "243"},
            {q: "Next number: 2, 8, 18, 32, 50, ?", opts: ["64", "72", "80", "88"], a: "72"},
            {q: "Missing number: 1, 2, 6, 24, 120, ?", opts: ["240", "360", "480", "720"], a: "720"},
            {q: "Next number: 0, 6, 24, 60, 120, ?", opts: ["180", "210", "240", "270"], a: "210"},
            {q: "Missing number: 1, 4, 13, 40, ?", opts: ["81", "100", "121", "144"], a: "121"},
            {q: "Next number: 3, 4, 7, 11, 18, ?", opts: ["25", "27", "29", "31"], a: "29"},
            {q: "Missing number: 2, 12, 36, 80, ?", opts: ["100", "120", "150", "180"], a: "150"},
            {q: "Next number: 1, 5, 14, 30, 55, ?", opts: ["77", "85", "91", "95"], a: "91"},
            {q: "Missing number: 1, 2, 4, 7, 11, 16, ?", opts: ["20", "22", "24", "26"], a: "22"},
            {q: "Next number: 2, 6, 12, 20, 30, 42, ?", opts: ["50", "54", "56", "60"], a: "56"},
            {q: "Missing number: 1, 3, 6, 10, 15, 21, ?", opts: ["25", "27", "28", "30"], a: "28"},
            {q: "Next number: 4, 9, 25, 49, 121, ?", opts: ["144", "169", "196", "225"], a: "169"},
            {q: "Missing number: 2, 3, 8, 63, ?", opts: ["3968", "3969", "3970", "3971"], a: "3968"},
            {q: "Next number: 1, 2, 6, 15, 31, ?", opts: ["46", "52", "56", "62"], a: "56"},
            {q: "Missing number: 3, 8, 15, 24, 35, ?", opts: ["46", "48", "50", "52"], a: "48"},
            {q: "Next number: 0, 1, 8, 27, 64, ?", opts: ["100", "121", "125", "128"], a: "125"},
            {q: "Missing number: 1, 1, 2, 4, 7, 13, 24, ?", opts: ["36", "40", "44", "48"], a: "44"}
        ],
        "Mixtures": [
            {q: "Mixture 20L milk+water, milk 25%. How much milk to add to make 40%?", opts: ["2.5L", "3L", "3.5L", "4L"], a: "2.5L"},
            {q: "Two alloys gold:silver=3:2 and 5:3. Mixed in ratio 2:1. Final ratio?", opts: ["21:13", "22:13", "23:14", "24:15"], a: "21:13"},
            {q: "40L mixture milk:water=3:1. How much water to add to make 1:1?", opts: ["15L", "20L", "25L", "30L"], a: "20L"},
            {q: "Sugar solution 20% sugar. 50L taken out, 50L water added. New concentration?", opts: ["10%", "12%", "15%", "18%"], a: "10%"},
            {q: "Two varieties rice Rs.30/kg and Rs.40/kg mixed in ratio 2:3. Price per kg?", opts: ["34", "35", "36", "37"], a: "36"},
            {q: "Alcohol solution 30%. How much pure alcohol to add to 60L to make 40%?", opts: ["8L", "10L", "12L", "15L"], a: "10L"},
            {q: "Mixture A(3:2), B(5:3) mixed in equal quantity. Final ratio?", opts: ["19:13", "20:13", "21:14", "22:15"], a: "19:13"},
            {q: "20% alcohol solution. If 4L water evaporated from 20L, new concentration?", opts: ["22%", "24%", "25%", "26%"], a: "25%"},
            {q: "Milk:water=4:1. If 10L mixture replaced with water, new ratio?", opts: ["3:2", "7:3", "5:3", "4:3"], a: "3:2"},
            {q: "Two liquids A:B=3:5 worth Rs.20/L and Rs.30/L. Mixture worth?", opts: ["26.25", "26.50", "26.75", "27.00"], a: "26.25"},
            {q: "Mixture 40L milk+water, milk 30%. How much water to add to make 20%?", opts: ["10L", "15L", "20L", "25L"], a: "20L"},
            {q: "Alloys copper:zinc=7:3 and 7:11 mixed in ratio 2:3. Final ratio?", opts: ["7:5", "14:9", "21:19", "28:23"], a: "7:5"},
            {q: "60L mixture milk:water=2:1. How much milk to add to make 4:1?", opts: ["20L", "25L", "30L", "35L"], a: "30L"},
            {q: "Salt solution 15% salt. 30L taken out, 30L water added. New concentration?", opts: ["7.5%", "10%", "12%", "15%"], a: "7.5%"},
            {q: "Two teas Rs.200/kg and Rs.300/kg mixed in ratio 3:2. Price per kg?", opts: ["230", "240", "250", "260"], a: "240"},
            {q: "Acid solution 25%. How much pure acid to add to 40L to make 40%?", opts: ["8L", "10L", "12L", "15L"], a: "10L"},
            {q: "Mixture A(2:1), B(3:2) mixed in ratio 1:2. Final ratio?", opts: ["7:5", "8:5", "9:5", "11:7"], a: "8:5"},
            {q: "30% sugar solution. If 6L water evaporated from 30L, new concentration?", opts: ["33.3%", "35%", "37.5%", "40%"], a: "37.5%"},
            {q: "Milk:water=5:2. If 14L mixture replaced with milk, new ratio?", opts: ["3:1", "7:2", "4:1", "9:2"], a: "3:1"},
            {q: "Two liquids P:Q=2:3 worth Rs.15/L and Rs.25/L. Mixture worth?", opts: ["19", "20", "21", "22"], a: "21"},
            {q: "Mixture 50L alcohol+water, alcohol 40%. How much alcohol to add to make 60%?", opts: ["20L", "25L", "30L", "35L"], a: "25L"},
            {q: "Alloys tin:lead=4:1 and 3:2 mixed in ratio 1:1. Final ratio?", opts: ["7:3", "8:3", "3:1", "10:3"], a: "7:3"},
            {q: "80L mixture milk:water=3:2. How much water to add to make 1:1?", opts: ["20L", "25L", "30L", "35L"], a: "20L"},
            {q: "Acid solution 20% acid. 25L taken out, 25L water added. New concentration?", opts: ["10%", "12%", "15%", "18%"], a: "10%"},
            {q: "Two coffees Rs.150/kg and Rs.250/kg mixed in ratio 4:1. Price per kg?", opts: ["170", "180", "190", "200"], a: "170"},
            {q: "Wine solution 15% alcohol. How much pure wine to add to 80L to make 25%?", opts: ["8L", "10L", "12L", "15L"], a: "10L"},
            {q: "Mixture X(5:3), Y(7:4) mixed in ratio 2:3. Final ratio?", opts: ["41:25", "43:26", "45:28", "47:29"], a: "41:25"},
            {q: "25% salt solution. If 5L water evaporated from 25L, new concentration?", opts: ["27.5%", "30%", "31.25%", "33.3%"], a: "31.25%"},
            {q: "Milk:water=7:3. If 15L mixture replaced with water, new ratio?", opts: ["2:1", "5:3", "3:2", "4:3"], a: "2:1"},
            {q: "Two oils A:B=4:5 worth Rs.40/L and Rs.60/L. Mixture worth?", opts: ["50", "52", "54", "56"], a: "52"},
            {q: "Mixture 30L spirit+water, spirit 70%. How much water to add to make 50%?", opts: ["10L", "12L", "15L", "18L"], a: "12L"},
            {q: "Alloys gold:silver=9:1 and 13:7 mixed in ratio 3:2. Final ratio?", opts: ["7:3", "8:3", "3:1", "10:3"], a: "7:3"},
            {q: "100L mixture milk:water=4:1. How much milk to add to make 9:1?", opts: ["25L", "30L", "35L", "40L"], a: "25L"},
            {q: "Sugar solution 30% sugar. 40L taken out, 40L water added. New concentration?", opts: ["15%", "18%", "20%", "22%"], a: "18%"},
            {q: "Two wheats Rs.12/kg and Rs.18/kg mixed in ratio 1:2. Price per kg?", opts: ["14", "15", "16", "17"], a: "16"},
            {q: "Alcohol solution 35%. How much pure alcohol to add to 100L to make 50%?", opts: ["25L", "30L", "35L", "40L"], a: "30L"},
            {q: "Mixture M(8:5), N(11:7) mixed in ratio 3:4. Final ratio?", opts: ["25:16", "26:17", "27:18", "28:19"], a: "25:16"},
            {q: "40% acid solution. If 8L water evaporated from 40L, new concentration?", opts: ["44.4%", "46.7%", "48%", "50%"], a: "50%"},
            {q: "Milk:water=9:4. If 26L mixture replaced with milk, new ratio?", opts: ["3:1", "7:2", "4:1", "9:2"], a: "3:1"},
            {q: "Two chemicals X:Y=5:6 worth Rs.30/L and Rs.45/L. Mixture worth?", opts: ["36", "37.5", "38.5", "40"], a: "37.5"}
        ],
        "Speed, Time & Distance": [
            {q: "Car travels 120km in 2 hours. Speed?", opts: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"], a: "60 km/h"},
            {q: "Train 150m long crosses pole in 15 seconds. Speed?", opts: ["36 km/h", "40 km/h", "44 km/h", "48 km/h"], a: "36 km/h"},
            {q: "A to B 300km. Car at 60 km/h, returns at 40 km/h. Average speed?", opts: ["48 km/h", "50 km/h", "52 km/h", "54 km/h"], a: "48 km/h"},
            {q: "Two trains 100m and 120m long running at 50 km/h and 40 km/h opposite directions. Time to cross?", opts: ["8.8 sec", "9.2 sec", "10.4 sec", "11.6 sec"], a: "8.8 sec"},
            {q: "Man rows 12km downstream in 2 hours, upstream in 3 hours. Speed in still water?", opts: ["4 km/h", "5 km/h", "6 km/h", "7 km/h"], a: "5 km/h"},
            {q: "Bus covers 360km in 6 hours. If speed increased by 20%, time for same distance?", opts: ["4 hours", "4.5 hours", "5 hours", "5.5 hours"], a: "5 hours"},
            {q: "Two cars start from same point at 40 km/h and 50 km/h opposite directions. After 3 hours, distance?", opts: ["270 km", "280 km", "290 km", "300 km"], a: "270 km"},
            {q: "Train crosses platform 200m long in 30 seconds. Speed 54 km/h. Train length?", opts: ["150 m", "200 m", "250 m", "300 m"], a: "250 m"},
            {q: "Boat speed 15 km/h, river speed 5 km/h. Time to go 60km downstream?", opts: ["3 hours", "3.5 hours", "4 hours", "4.5 hours"], a: "3 hours"},
            {q: "Walking at 5/6 usual speed, man late by 10 minutes. Usual time?", opts: ["50 min", "55 min", "60 min", "65 min"], a: "50 min"},
            {q: "Two trains 120m and 80m long running same direction at 40 km/h and 30 km/h. Time to cross?", opts: ["60 sec", "65 sec", "70 sec", "72 sec"], a: "72 sec"},
            {q: "Car covers first half at 40 km/h, second half at 60 km/h. Average speed?", opts: ["46 km/h", "48 km/h", "50 km/h", "52 km/h"], a: "48 km/h"},
            {q: "Man reaches station 5 minutes early walking at 4 km/h, 7 minutes late at 3 km/h. Distance to station?", opts: ["2 km", "2.2 km", "2.4 km", "2.6 km"], a: "2.4 km"},
            {q: "Two cyclists start towards each other at 20 km/h and 25 km/h. Meeting after 2 hours. Initial distance?", opts: ["80 km", "85 km", "90 km", "95 km"], a: "90 km"},
            {q: "Train 200m long crosses another 150m long in 20 seconds same direction. Speed difference?", opts: ["15 km/h", "18 km/h", "20 km/h", "22 km/h"], a: "18 km/h"},
            {q: "Boat goes 24km upstream and 28km downstream in 6 hours. Goes 30km upstream and 21km downstream in 6.5 hours. Speed of boat?", opts: ["8 km/h", "9 km/h", "10 km/h", "11 km/h"], a: "10 km/h"},
            {q: "Walking at 3/4 usual speed, man takes 20 minutes more. Distance?", opts: ["3 km", "4 km", "5 km", "6 km"], a: "3 km"},
            {q: "Two trains from A and B towards each other at 60 km/h and 80 km/h. When meet, first traveled 180km. Distance AB?", opts: ["380 km", "400 km", "420 km", "440 km"], a: "420 km"},
            {q: "Train 150m long passes pole in 10 seconds. Time to pass platform 250m long?", opts: ["20 sec", "25 sec", "30 sec", "35 sec"], a: "25 sec"},
            {q: "Speed ratio car:bus=5:4. Car takes 2 hours less for 400km. Bus speed?", opts: ["40 km/h", "45 km/h", "50 km/h", "55 km/h"], a: "40 km/h"},
            {q: "Two cars same direction at 45 km/h and 60 km/h. Faster starts 3 hours later. Overtaking time?", opts: ["6 hours", "7 hours", "8 hours", "9 hours"], a: "9 hours"},
            {q: "Man rows to place 30km away and back in 10 hours. Speed downstream 6 km/h, upstream 4 km/h. Distance he rows?", opts: ["24 km", "25 km", "26 km", "28 km"], a: "24 km"},
            {q: "Train 100m long crosses man running at 5 km/h same direction in 10 seconds. Train speed?", opts: ["35 km/h", "38 km/h", "40 km/h", "42 km/h"], a: "41 km/h"},
            {q: "Walking at 6 km/h, man reaches 10 minutes early. At 4 km/h, 20 minutes late. Distance?", opts: ["5 km", "6 km", "7 km", "8 km"], a: "6 km"},
            {q: "Two trains length 200m and 250m cross in 18 seconds opposite directions. Speeds ratio 2:3. Faster train speed?", opts: ["50 km/h", "54 km/h", "60 km/h", "66 km/h"], a: "60 km/h"},
            {q: "Car covers distance at 60 km/h and returns at 40 km/h. Average speed?", opts: ["46 km/h", "48 km/h", "50 km/h", "52 km/h"], a: "48 km/h"},
            {q: "Two cyclists 20km apart approach at 10 km/h and 15 km/h. Fly at 25 km/h starts with first, touches second and returns. Total distance fly?", opts: ["20 km", "25 km", "30 km", "35 km"], a: "25 km"},
            {q: "Train crosses pole in 15 seconds, platform 100m long in 25 seconds. Length?", opts: ["100 m", "120 m", "140 m", "150 m"], a: "150 m"},
            {q: "Boat speed 12 km/h, river 3 km/h. Time for 45km downstream and return?", opts: ["6 hours", "7 hours", "8 hours", "9 hours"], a: "8 hours"},
            {q: "Speed increased by 5 km/h, saves 1 hour for 300km. Original speed?", opts: ["20 km/h", "25 km/h", "30 km/h", "35 km/h"], a: "25 km/h"},
            {q: "Two trains from A and B at 70 km/h and 80 km/h. When meet, second traveled 240km. Distance AB?", opts: ["510 km", "520 km", "530 km", "540 km"], a: "530 km"},
            {q: "Train 200m long crosses another 300m long in 30 seconds same direction. Speed difference?", opts: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"], a: "60 km/h"},
            {q: "Walking at 5 km/h, reaches 15 minutes late. At 6 km/h, 10 minutes early. Distance?", opts: ["10 km", "11 km", "12 km", "13 km"], a: "12.5 km"},
            {q: "Two cars opposite directions at 50 km/h and 60 km/h. After 2.5 hours, distance?", opts: ["265 km", "270 km", "275 km", "280 km"], a: "275 km"},
            {q: "Train crosses platform in 20 seconds, man on platform in 8 seconds. Length ratio?", opts: ["2:3", "3:4", "4:5", "5:6"], a: "2:3"},
            {q: "Boat goes 15km upstream and 22km downstream in 5 hours. Goes 20km upstream and 33km downstream in 7 hours. River speed?", opts: ["2 km/h", "3 km/h", "4 km/h", "5 km/h"], a: "3 km/h"},
            {q: "Speed decreased by 4 km/h, takes 1 hour more for 120km. Original speed?", opts: ["20 km/h", "22 km/h", "24 km/h", "26 km/h"], a: "24 km/h"},
            {q: "Two trains length 150m and 200m cross in 25 seconds same direction. Speeds ratio 3:4. Slower train speed?", opts: ["36 km/h", "40 km/h", "44 km/h", "48 km/h"], a: "36 km/h"},
            {q: "Car covers 1/3 distance at 30 km/h, rest at 60 km/h. Average speed?", opts: ["40 km/h", "42 km/h", "45 km/h", "48 km/h"], a: "45 km/h"},
            {q: "Two places A and B. Man from A to B at 4 km/h, returns at 6 km/h. Average speed?", opts: ["4.5 km/h", "4.8 km/h", "5 km/h", "5.2 km/h"], a: "4.8 km/h"}
        ]
    },
    technical: {
        "OOP Concepts": [
            {q: "Four main OOP principles?"},
            {q: "Difference between abstraction and encapsulation?"},
            {q: "What is polymorphism? Types?"},
            {q: "Advantages of inheritance?"},
            {q: "Method overloading vs overriding?"},
            {q: "What are abstract classes and interfaces?"},
            {q: "What is constructor? Types?"},
            {q: "What is encapsulation with real example?"},
            {q: "Difference between class and object?"},
            {q: "What is multiple inheritance? Supported in Java?"},
            {q: "What is association, aggregation, composition?"},
            {q: "What are access modifiers?"},
            {q: "What is method hiding?"},
            {q: "What is coupling and cohesion?"},
            {q: "What is the 'is-a' and 'has-a' relationship?"},
            {q: "What are static methods and variables?"},
            {q: "What is method signature?"},
            {q: "What is object cloning?"},
            {q: "What are wrapper classes?"},
            {q: "What is the 'final' keyword?"},
            {q: "What are packages?"},
            {q: "What is method chaining?"},
            {q: "What are instance initializer blocks?"},
            {q: "What is object serialization?"},
            {q: "What are anonymous classes?"},
            {q: "What is the 'super' keyword?"},
            {q: "What are immutable objects?"},
            {q: "What is the 'this' keyword?"},
            {q: "What are enums?"},
            {q: "What are annotations?"},
            {q: "What is reflection?"},
            {q: "What are design patterns?"},
            {q: "What is singleton pattern?"},
            {q: "What is factory pattern?"},
            {q: "What is MVC pattern?"},
            {q: "What is dependency injection?"},
            {q: "What is solid principles?"},
            {q: "What is law of demeter?"},
            {q: "What is composition vs inheritance?"},
            {q: "What are lambda expressions?"}
        ],
        "Data Structures": [
            {q: "Compare arrays and linked lists"},
            {q: "What is binary search tree and properties?"},
            {q: "How hash table works and time complexity?"},
            {q: "Types of tree traversals and uses?"},
            {q: "What is heap data structure?"},
            {q: "Difference between stack and queue?"},
            {q: "What is graph? Types of graphs?"},
            {q: "Time complexity of binary search?"},
            {q: "What is AVL tree?"},
            {q: "Applications of stack data structure?"},
            {q: "What is trie data structure?"},
            {q: "What is red-black tree?"},
            {q: "What is B-tree?"},
            {q: "What is skip list?"},
            {q: "What is segment tree?"},
            {q: "What is union-find data structure?"},
            {q: "What is priority queue?"},
            {q: "What is circular linked list?"},
            {q: "What is doubly linked list?"},
            {q: "What is adjacency list vs matrix?"},
            {q: "What is topological sorting?"},
            {q: "What is minimum spanning tree?"},
            {q: "What is dynamic array?"},
            {q: "What is bloom filter?"},
            {q: "What is LRU cache?"},
            {q: "What is circular buffer?"},
            {q: "What is suffix tree?"},
            {q: "What is Fenwick tree?"},
            {q: "What is graph coloring?"},
            {q: "What is Dijkstra's algorithm?"},
            {q: "What is Bellman-Ford algorithm?"},
            {q: "What is Floyd-Warshall algorithm?"},
            {q: "What is Kruskal's algorithm?"},
            {q: "What is Prim's algorithm?"},
            {q: "What is A* search algorithm?"},
            {q: "What is BFS vs DFS?"},
            {q: "What is backtracking?"},
            {q: "What is divide and conquer?"},
            {q: "What is greedy algorithm?"}
        ],
        "Algorithms": [
            {q: "Difference between DFS and BFS?"},
            {q: "Time complexity of quicksort average/worst case?"},
            {q: "Dynamic programming vs divide and conquer?"},
            {q: "How Dijkstra's algorithm works?"},
            {q: "What is greedy algorithm?"},
            {q: "Binary search time complexity?"},
            {q: "What is backtracking algorithm?"},
            {q: "How merge sort works?"},
            {q: "What is memoization?"},
            {q: "Time complexity of bubble sort?"},
            {q: "What is Kadane's algorithm?"},
            {q: "What is Knuth-Morris-Pratt algorithm?"},
            {q: "What is Rabin-Karp algorithm?"},
            {q: "What is longest common subsequence?"},
            {q: "What is longest increasing subsequence?"},
            {q: "What is 0/1 knapsack problem?"},
            {q: "What is coin change problem?"},
            {q: "What is edit distance?"},
            {q: "What is Floyd's cycle detection?"},
            {q: "What is topological sort?"},
            {q: "What is heap sort?"},
            {q: "What is counting sort?"},
            {q: "What is radix sort?"},
            {q: "What is bucket sort?"},
            {q: "What is shell sort?"},
            {q: "What is insertion sort?"},
            {q: "What is selection sort?"},
            {q: "What is quickselect algorithm?"},
            {q: "What is Boyer-Moore voting algorithm?"},
            {q: "What is reservoir sampling?"},
            {q: "What is FFT algorithm?"},
            {q: "What is Euclidean algorithm?"},
            {q: "What is Sieve of Eratosthenes?"},
            {q: "What is Monte Carlo algorithm?"},
            {q: "What is Las Vegas algorithm?"},
            {q: "What is branch and bound?"},
            {q: "What is simulated annealing?"},
            {q: "What is genetic algorithm?"}
        ],
        "System Design": [
            {q: "What is load balancer and why use it?"},
            {q: "Explain microservices architecture"},
            {q: "What is database indexing?"},
            {q: "CAP theorem explanation"},
            {q: "What is caching? Types?"},
            {q: "Explain REST API principles"},
            {q: "What is database normalization?"},
            {q: "Scalability vs availability"},
            {q: "What is CDN?"},
            {q: "Database replication types?"},
            {q: "What is sharding?"},
            {q: "What is consistent hashing?"},
            {q: "What is message queue?"},
            {q: "What is API gateway?"},
            {q: "What is circuit breaker pattern?"},
            {q: "What is service discovery?"},
            {q: "What is rate limiting?"},
            {q: "What is database partitioning?"},
            {q: "What is eventual consistency?"},
            {q: "What is ACID vs BASE?"},
            {q: "What is distributed system?"},
            {q: "What is MapReduce?"},
            {q: "What is consensus algorithm?"},
            {q: "What is Paxos algorithm?"},
            {q: "What is Raft algorithm?"},
            {q: "What is gossip protocol?"},
            {q: "What is leader election?"},
            {q: "What is heartbeats in distributed systems?"},
            {q: "What is two-phase commit?"},
            {q: "What is three-phase commit?"},
            {q: "What is idempotency?"},
            {q: "What is backpressure?"},
            {q: "What is data consistency models?"},
            {q: "What is database isolation levels?"},
            {q: "What is deadlock in distributed systems?"},
            {q: "What is Byzantine fault tolerance?"},
            {q: "What is quorum in distributed systems?"},
            {q: "What is vector clocks?"},
            {q: "What is conflict-free replicated data types?"}
        ],
        "Database": [
            {q: "ACID properties in DBMS"},
            {q: "Difference between SQL and NoSQL"},
            {q: "What are database indexes?"},
            {q: "Types of SQL joins"},
            {q: "What is transaction?"},
            {q: "Normalization forms"},
            {q: "What is view in SQL?"},
            {q: "Difference between primary key and foreign key"},
            {q: "What is trigger?"},
            {q: "SQL vs MySQL difference?"},
            {q: "What is stored procedure?"},
            {q: "What is cursor?"},
            {q: "What is database locking?"},
            {q: "What is deadlock in database?"},
            {q: "What is database isolation levels?"},
            {q: "What is database replication?"},
            {q: "What is database sharding?"},
            {q: "What is database partitioning?"},
            {q: "What is database clustering?"},
            {q: "What is database mirroring?"},
            {q: "What is database backup types?"},
            {q: "What is database recovery?"},
            {q: "What is database concurrency control?"},
            {q: "What is database transaction states?"},
            {q: "What is database schema?"},
            {q: "What is database instance?"},
            {q: "What is database cursor?"},
            {q: "What is database constraint?"},
            {q: "What is database index types?"},
            {q: "What is database view materialization?"},
            {q: "What is database query optimization?"},
            {q: "What is database execution plan?"},
            {q: "What is database statistics?"},
            {q: "What is database hint?"},
            {q: "What is database connection pooling?"},
            {q: "What is database ORM?"},
            {q: "What is database migration?"},
            {q: "What is database seeding?"},
            {q: "What is database versioning?"},
            {q: "What is database testing?"}
        ],
        "Networking": [
            {q: "TCP vs UDP differences"},
            {q: "What is HTTP and HTTPS?"},
            {q: "Explain DNS working"},
            {q: "What is VPN?"},
            {q: "OSI model layers"},
            {q: "TCP 3-way handshake"},
            {q: "What is subnetting?"},
            {q: "Difference between router and switch"},
            {q: "What is firewall?"},
            {q: "HTTP status codes"},
            {q: "What is SSL/TLS?"},
            {q: "What is IP addressing?"},
            {q: "What is NAT?"},
            {q: "What is DHCP?"},
            {q: "What is ARP?"},
            {q: "What is ICMP?"},
            {q: "What is BGP?"},
            {q: "What is OSPF?"},
            {q: "What is VLAN?"},
            {q: "What is QoS?"},
            {q: "What is MPLS?"},
            {q: "What is CDN?"},
            {q: "What is load balancing?"},
            {q: "What is proxy server?"},
            {q: "What is reverse proxy?"},
            {q: "What is socket programming?"},
            {q: "What is REST vs SOAP?"},
            {q: "What is WebSocket?"},
            {q: "What is HTTP/2?"},
            {q: "What is QUIC?"},
            {q: "What is DNS caching?"},
            {q: "What is DNS record types?"},
            {q: "What is SMTP?"},
            {q: "What is FTP?"},
            {q: "What is SSH?"},
            {q: "What is Telnet?"},
            {q: "What is RPC?"},
            {q: "What is API gateway?"},
            {q: "What is microservices communication?"},
            {q: "What is service mesh?"}
        ],
        "OS Concepts": [
            {q: "Process vs thread differences"},
            {q: "What is deadlock?"},
            {q: "Memory management techniques"},
            {q: "Scheduling algorithms"},
            {q: "Virtual memory concept"},
            {q: "What is semaphore?"},
            {q: "Paging vs segmentation"},
            {q: "What is kernel?"},
            {q: "Context switching"},
            {q: "Producer-consumer problem"},
            {q: "What is mutex?"},
            {q: "What is monitor?"},
            {q: "What is critical section?"},
            {q: "What is race condition?"},
            {q: "What is synchronization?"},
            {q: "What is inter-process communication?"},
            {q: "What is shared memory?"},
            {q: "What is message passing?"},
            {q: "What is pipe?"},
            {q: "What is signal?"},
            {q: "What is socket?"},
            {q: "What is file system?"},
            {q: "What is inode?"},
            {q: "What is RAID?"},
            {q: "What is system call?"},
            {q: "What is interrupt?"},
            {q: "What is DMA?"},
            {q: "What is cache memory?"},
            {q: "What is TLB?"},
            {q: "What is page table?"},
            {q: "What is page fault?"},
            {q: "What is thrashing?"},
            {q: "What is swapping?"},
            {q: "What is fragmentation?"},
            {q: "What is boot process?"},
            {q: "What is shell?"},
            {q: "What is kernel panic?"},
            {q: "What is system daemon?"},
            {q: "What is process states?"},
            {q: "What is process control block?"},
            {q: "What is thread pool?"},
            {q: "What is green threads?"}
        ]
    },
    coding: {
        "Arrays": [
            {q: "Find maximum subarray sum"},
            {q: "Rotate array by k positions"},
            {q: "Find pairs summing to specific value"},
            {q: "Find element appearing more than n/2 times"},
            {q: "Merge two sorted arrays"},
            {q: "Find missing number in array"},
            {q: "Move zeros to end"},
            {q: "Product of array except self"},
            {q: "Find duplicate number"},
            {q: "Container with most water"},
            {q: "Trapping rain water problem"},
            {q: "Maximum product subarray"},
            {q: "Search in rotated sorted array"},
            {q: "Find minimum in rotated sorted array"},
            {q: "3Sum problem"},
            {q: "Remove duplicates from sorted array"},
            {q: "Best time to buy and sell stock"},
            {q: "Find all duplicates in array"},
            {q: "Find the duplicate number"},
            {q: "Set matrix zeros"},
            {q: "Spiral matrix traversal"},
            {q: "Rotate image"},
            {q: "Word search in grid"},
            {q: "Longest consecutive sequence"},
            {q: "First missing positive"},
            {q: "Find peak element"},
            {q: "Search 2D matrix"},
            {q: "Kth largest element in array"},
            {q: "Top K frequent elements"},
            {q: "Find median from data stream"},
            {q: "Sliding window maximum"},
            {q: "Minimum window substring"},
            {q: "Subarray sum equals K"},
            {q: "Find all anagrams in string"},
            {q: "Longest substring without repeating characters"},
            {q: "Minimum size subarray sum"},
            {q: "Permutations of array"},
            {q: "Subsets of array"},
            {q: "Combination sum"},
            {q: "Jump game"}
        ],
        "Strings": [
            {q: "Check if string is palindrome"},
            {q: "Longest substring without repeating characters"},
            {q: "Check if two strings are anagrams"},
            {q: "String compression algorithm"},
            {q: "Longest palindromic substring"},
            {q: "String to integer conversion"},
            {q: "Valid parentheses check"},
            {q: "Group anagrams"},
            {q: "Longest common prefix"},
            {q: "Minimum window substring"},
            {q: "Valid palindrome II"},
            {q: "First unique character in string"},
            {q: "Reverse string"},
            {q: "Reverse words in string"},
            {q: "Valid anagram"},
            {q: "Longest repeating character replacement"},
            {q: "Find all anagrams in string"},
            {q: "Minimum insertions to make palindrome"},
            {q: "String rotation check"},
            {q: "Count and say problem"},
            {q: "Implement strStr()"},
            {q: "Roman to integer conversion"},
            {q: "Integer to roman conversion"},
            {q: "Zigzag conversion"},
            {q: "Find first occurrence in string"},
            {q: "Regular expression matching"},
            {q: "Wildcard matching"},
            {q: "Valid number"},
            {q: "Text justification"},
            {q: "Simplify path"},
            {q: "Decode ways"},
            {q: "Letter combinations of phone number"},
            {q: "Generate parentheses"},
            {q: "Word break problem"},
            {q: "Word search II"},
            {q: "Palindrome partitioning"},
            {q: "Restore IP addresses"},
            {q: "String permutations"},
            {q: "String subsets"},
            {q: "Minimum deletions to make valid string"}
        ],
        "Trees": [
            {q: "Check if binary tree is BST"},
            {q: "Find lowest common ancestor"},
            {q: "Serialize and deserialize binary tree"},
            {q: "Check if binary tree is balanced"},
            {q: "Level order traversal"},
            {q: "Diameter of binary tree"},
            {q: "Inorder traversal iterative"},
            {q: "Maximum depth of binary tree"},
            {q: "Binary tree right side view"},
            {q: "Construct tree from inorder-preorder"},
            {q: "Validate binary search tree"},
            {q: "Convert sorted array to BST"},
            {q: "Binary tree maximum path sum"},
            {q: "Symmetric tree check"},
            {q: "Invert binary tree"},
            {q: "Path sum problems"},
            {q: "Count complete tree nodes"},
            {q: "Binary tree zigzag level order"},
            {q: "Kth smallest element in BST"},
            {q: "BST iterator implementation"},
            {q: "Delete node in BST"},
            {q: "Insert into BST"},
            {q: "Search in BST"},
            {q: "Closest BST value"},
            {q: "Convert BST to sorted DLL"},
            {q: "Merge two binary trees"},
            {q: "Subtree of another tree"},
            {q: "Tree traversal iterative methods"},
            {q: "Construct BST from preorder"},
            {q: "Unique BSTs count"},
            {q: "Binary tree cameras"},
            {q: "House robber III"},
            {q: "Vertical order traversal"},
            {q: "Boundary traversal"},
            {q: "Top view of binary tree"},
            {q: "Bottom view of binary tree"},
            {q: "Left view of binary tree"},
            {q: "Right view of binary tree"},
            {q: "Diagonal traversal"},
            {q: "Morris traversal"}
        ],
        "Graphs": [
            {q: "Implement BFS traversal"},
            {q: "Implement DFS traversal"},
            {q: "Detect cycle in directed graph"},
            {q: "Find shortest path in unweighted graph"},
            {q: "Topological sort algorithm"},
            {q: "Number of connected components"},
            {q: "Dijkstra's algorithm implementation"},
            {q: "Clone a graph"},
            {q: "Course schedule problem"},
            {q: "Word ladder problem"},
            {q: "Number of islands"},
            {q: "Pacific Atlantic water flow"},
            {q: "Graph valid tree"},
            {q: "Alien dictionary"},
            {q: "Cheapest flights within K stops"},
            {q: "Network delay time"},
            {q: "Critical connections in network"},
            {q: "Word search in grid"},
            {q: "Surrounded regions"},
            {q: "Walls and gates"},
            {q: "Minimum height trees"},
            {q: "Reconstruct itinerary"},
            {q: "Evaluate division"},
            {q: "Redundant connection"},
            {q: "Course schedule II"},
            {q: "Sequence reconstruction"},
            {q: "Graph bipartite check"},
            {q: "Is graph bipartite?"},
            {q: "Floyd Warshall algorithm"},
            {q: "Bellman Ford algorithm"},
            {q: "Prim's algorithm MST"},
            {q: "Kruskal's algorithm MST"},
            {q: "Articulation points"},
            {q: "Bridges in graph"},
            {q: "Strongly connected components"},
            {q: "Eulerian path and circuit"},
            {q: "Hamiltonian path and cycle"},
            {q: "Traveling salesman problem"},
            {q: "Minimum spanning tree"},
            {q: "Maximum flow problem"}
        ],
        "Dynamic Programming": [
            {q: "Fibonacci sequence using DP"},
            {q: "0/1 knapsack problem"},
            {q: "Longest common subsequence"},
            {q: "Coin change problem"},
            {q: "Longest increasing subsequence"},
            {q: "Edit distance problem"},
            {q: "House robber problem"},
            {q: "Maximum product subarray"},
            {q: "Unique paths in grid"},
            {q: "Word break problem"},
            {q: "Climbing stairs problem"},
            {q: "Minimum path sum in grid"},
            {q: "Coin change II (number of combinations)"},
            {q: "Target sum problem"},
            {q: "Partition equal subset sum"},
            {q: "Longest palindromic subsequence"},
            {q: "Wildcard matching DP solution"},
            {q: "Regular expression matching DP"},
            {q: "Best time to buy/sell stock with cooldown"},
            {q: "Longest common substring"},
            {q: "Maximum subarray sum (Kadane's)"},
            {q: "Egg dropping problem"},
            {q: "Palindrome partitioning II"},
            {q: "Word break II"},
            {q: "Burst balloons"},
            {q: "Minimum insertion steps to make palindrome"},
            {q: "Distinct subsequences"},
            {q: "Interleaving string"},
            {q: "Maximum length of repeated subarray"},
            {q: "Count different palindromic subsequences"},
            {q: "Minimum cost to cut stick"},
            {q: "Stone game problems"},
            {q: "Minimum falling path sum"},
            {q: "Triangle minimum path sum"},
            {q: "Paint house problems"},
            {q: "Decode ways II"},
            {q: "Perfect squares"},
            {q: "Integer break"},
            {q: "Count numbers with unique digits"},
            {q: "Range sum query 2D"}
        ],
        "Sorting": [
            {q: "Implement quick sort"},
            {q: "Implement merge sort"},
            {q: "Implement bubble sort"},
            {q: "When to use which sorting algorithm?"},
            {q: "Stable vs unstable sorting"},
            {q: "Count sort implementation"},
            {q: "Heap sort algorithm"},
            {q: "Radix sort working"},
            {q: "Sort colors problem"},
            {q: "Kth largest element in array"},
            {q: "Top K frequent elements"},
            {q: "Merge intervals"},
            {q: "Insert interval"},
            {q: "Non-overlapping intervals"},
            {q: "Meeting rooms problems"},
            {q: "Minimum number of arrows to burst balloons"},
            {q: "Sort list (linked list)"},
            {q: "Largest number from array"},
            {q: "H-index calculation"},
            {q: "Wiggle sort"},
            {q: "K closest points to origin"},
            {q: "Sort characters by frequency"},
            {q: "Custom sort string"},
            {q: "Sort array by parity"},
            {q: "Sort array by increasing frequency"},
            {q: "Maximum gap (bucket sort)"},
            {q: "Find right interval"},
            {q: "Count of smaller numbers after self"},
            {q: "Reverse pairs count"},
            {q: "Sort trans formed array"},
            {q: "Sort items by groups respecting dependencies"},
            {q: "Minimum swaps to sort array"},
            {q: "Sort matrix diagonally"},
            {q: "Sort the Jumbled numbers"},
            {q: "Sort integers by the power value"},
            {q: "Sort array by bits count"},
            {q: "Sort linked list in O(n log n)"},
            {q: "External sorting algorithms"},
            {q: "Tim sort algorithm"},
            {q: "Shell sort implementation"}
        ],
        "Recursion": [
            {q: "Factorial using recursion"},
            {q: "Fibonacci using recursion"},
            {q: "Tower of Hanoi problem"},
            {q: "Generate all subsets"},
            {q: "Generate permutations"},
            {q: "Sudoku solver using backtracking"},
            {q: "N-Queens problem"},
            {q: "Generate parentheses"},
            {q: "Letter combinations of phone number"},
            {q: "Power set using recursion"},
            {q: "Combination sum problems"},
            {q: "Palindrome partitioning"},
            {q: "Word search backtracking"},
            {q: "Regular expression matching recursion"},
            {q: "Wildcard matching recursion"},
            {q: "Solve sudoku"},
            {q: "N-Queens II (count solutions)"},
            {q: "Permutations II (with duplicates)"},
            {q: "Subsets II (with duplicates)"},
            {q: "Combination sum II"},
            {q: "Combination sum III"},
            {q: "Restore IP addresses"},
            {q: "Additive number"},
            {q: "Word break II backtracking"},
            {q: "Remove invalid parentheses"},
            {q: "Expression add operators"},
            {q: "Strobogrammatic number II"},
            {q: "Generalized abbreviation"},
            {q: "Flip game II"},
            {q: "Can I win game"},
            {q: "Matchsticks to square"},
            {q: "Partition to K equal sum subsets"},
            {q: "Beautiful arrangement"},
            {q: "Target sum backtracking"},
            {q: "Palindrome permutation II"},
            {q: "Number of squareful arrays"},
            {q: "Maximum length of concatenated string"},
            {q: "Gray code generation"},
            {q: "Different ways to add parentheses"}
        ],
        "Linked Lists": [
            {q: "Reverse a linked list"},
            {q: "Detect cycle in linked list"},
            {q: "Merge two sorted linked lists"},
            {q: "Find middle of linked list"},
            {q: "Remove nth node from end"},
            {q: "Add two numbers represented as linked lists"},
            {q: "Palindrome linked list check"},
            {q: "Intersection of two linked lists"},
            {q: "LRU cache implementation"},
            {q: "Flatten a multilevel linked list"},
            {q: "Copy list with random pointer"},
            {q: "Rotate list"},
            {q: "Remove duplicates from sorted list"},
            {q: "Remove duplicates from unsorted list"},
            {q: "Swap nodes in pairs"},
            {q: "Reverse nodes in k-group"},
            {q: "Reorder list"},
            {q: "Sort list (merge sort)"},
            {q: "Insertion sort list"},
            {q: "Partition list"},
            {q: "Odd even linked list"},
            {q: "Split linked list in parts"},
            {q: "Next greater node in linked list"},
            {q: "Remove linked list elements"},
            {q: "Design linked list"},
            {q: "Linked list cycle II (find start)"},
            {q: "Intersection of two linked lists II"},
            {q: "Palindrome linked list O(1) space"},
            {q: "Convert sorted list to BST"},
            {q: "Flatten binary tree to linked list"},
            {q: "Design browser history"},
            {q: "Design phone directory"},
            {q: "Design snake game"},
            {q: "Design twitter"},
            {q: "Design underground system"},
            {q: "Design authentication manager"},
            {q: "Design file system"},
            {q: "Design search autocomplete"},
            {q: "Design rate limiter"},
            {q: "Design hit counter"}
        ]
    },
    behavioral: {
        "Teamwork": [
            {q: "Work with someone different personality"},
            {q: "Collaborate with difficult team member"},
            {q: "Handle team conflict"},
            {q: "Rely on team members for work"},
            {q: "Handle team member not contributing"},
            {q: "Work in cross-functional team"},
            {q: "Give constructive feedback to teammate"},
            {q: "Receive negative feedback from team"},
            {q: "Deal with underperforming team member"},
            {q: "Build trust within team"},
            {q: "Handle cultural differences in team"},
            {q: "Work with remote team members"},
            {q: "Manage team with different time zones"},
            {q: "Handle team member personal issues"},
            {q: "Balance team workload"},
            {q: "Motivate team during difficult project"},
            {q: "Celebrate team successes"},
            {q: "Handle team member leaving"},
            {q: "Integrate new team members"},
            {q: "Handle team member competing priorities"},
            {q: "Manage team expectations"},
            {q: "Handle team communication breakdown"},
            {q: "Work with team member who has different work style"},
            {q: "Handle team member taking credit for your work"},
            {q: "Support team member struggling with task"},
            {q: "Delegate tasks effectively in team"},
            {q: "Handle team member missing deadlines"},
            {q: "Build team cohesion"},
            {q: "Handle team member resistance to change"},
            {q: "Manage team during organizational changes"},
            {q: "Handle team member overstepping boundaries"},
            {q: "Work with team member who micro-manages"},
            {q: "Handle team member not following processes"},
            {q: "Manage team creative differences"},
            {q: "Handle team member burnout"},
            {q: "Work with team member who is always negative"},
            {q: "Handle team member who dominates discussions"},
            {q: "Manage team member who is too quiet"},
            {q: "Handle team member personal conflicts"},
            {q: "Build psychological safety in team"}
        ],
        "Leadership": [
            {q: "Lead team through difficult situation"},
            {q: "Persuade group to adopt your idea"},
            {q: "Take initiative beyond responsibilities"},
            {q: "Make decision without all information"},
            {q: "Mentor junior team members"},
            {q: "Handle team under pressure"},
            {q: "Delegate tasks effectively"},
            {q: "Motivate demotivated team"},
            {q: "Handle responsibility failure"},
            {q: "Lead without authority"},
            {q: "Handle difficult stakeholder"},
            {q: "Make unpopular decision"},
            {q: "Handle team resistance to change"},
            {q: "Build team vision and strategy"},
            {q: "Handle competing priorities from management"},
            {q: "Manage upward communication"},
            {q: "Handle budget constraints"},
            {q: "Lead innovation initiative"},
            {q: "Handle team member promotion decisions"},
            {q: "Manage team performance reviews"},
            {q: "Handle team restructuring"},
            {q: "Lead cross-functional project"},
            {q: "Handle ethical dilemma in leadership"},
            {q: "Manage team through acquisition/merger"},
            {q: "Handle public speaking for team"},
            {q: "Lead remote team effectively"},
            {q: "Handle team member career development"},
            {q: "Manage team during crisis"},
            {q: "Handle confidential information as leader"},
            {q: "Build leadership pipeline in team"},
            {q: "Handle team member asking for raise"},
            {q: "Manage team expectations from management"},
            {q: "Handle team working with external vendors"},
            {q: "Lead team through technology transition"},
            {q: "Handle team member wanting transfer"},
            {q: "Manage team during organizational politics"},
            {q: "Handle team member personal crisis"},
            {q: "Lead team through product launch"},
            {q: "Handle team working on legacy system"},
            {q: "Build team technical excellence"}
        ],
        "Conflict Resolution": [
            {q: "Disagreement with supervisor"},
            {q: "Handle conflict between team members"},
            {q: "Respond to negative feedback"},
            {q: "Work with someone you don't get along"},
            {q: "Handle unfair criticism"},
            {q: "Deal with office politics"},
            {q: "Handle competing priorities"},
            {q: "Manage stakeholder conflicts"},
            {q: "Resolve technical disagreements"},
            {q: "Handle personality clashes"},
            {q: "Handle conflict over resource allocation"},
            {q: "Resolve schedule conflicts"},
            {q: "Handle conflict over design decisions"},
            {q: "Manage conflict with external team"},
            {q: "Handle conflict over project ownership"},
            {q: "Resolve communication misunderstandings"},
            {q: "Handle conflict over quality standards"},
            {q: "Manage conflict over process changes"},
            {q: "Handle conflict with difficult client"},
            {q: "Resolve conflict over credit assignment"},
            {q: "Handle conflict over technical debt"},
            {q: "Manage conflict during code review"},
            {q: "Handle conflict over testing approach"},
            {q: "Resolve conflict over deployment strategy"},
            {q: "Handle conflict over documentation standards"},
            {q: "Manage conflict during agile ceremonies"},
            {q: "Handle conflict over performance metrics"},
            {q: "Resolve conflict over tool selection"},
            {q: "Handle conflict over architectural decisions"},
            {q: "Manage conflict during incident response"},
            {q: "Handle conflict over security requirements"},
            {q: "Resolve conflict over accessibility standards"},
            {q: "Handle conflict over internationalization"},
            {q: "Manage conflict over scalability requirements"},
            {q: "Handle conflict over maintainability"},
            {q: "Resolve conflict over code style"},
            {q: "Handle conflict over testing coverage"},
            {q: "Manage conflict over documentation quality"},
            {q: "Handle conflict over deployment frequency"},
            {q: "Resolve conflict over monitoring approach"}
        ],
        "Experience": [
            {q: "Most challenging project worked on"},
            {q: "Biggest accomplishment"},
            {q: "Describe your work experience"},
            {q: "Technical skills and expertise"},
            {q: "Project you're most proud of"},
            {q: "Experience with agile methodology"},
            {q: "Handling tight deadlines"},
            {q: "Learning new technology quickly"},
            {q: "Working in fast-paced environment"},
            {q: "Experience with remote work"},
            {q: "Experience with large codebases"},
            {q: "Working with legacy systems"},
            {q: "Experience with cloud technologies"},
            {q: "Working in startup environment"},
            {q: "Experience with enterprise software"},
            {q: "Working with cross-functional teams"},
            {q: "Experience with DevOps practices"},
            {q: "Working in regulated industries"},
            {q: "Experience with security practices"},
            {q: "Working with international teams"},
            {q: "Experience with mobile development"},
            {q: "Working on high-traffic systems"},
            {q: "Experience with database design"},
            {q: "Working on real-time systems"},
            {q: "Experience with machine learning"},
            {q: "Working on payment systems"},
            {q: "Experience with e-commerce platforms"},
            {q: "Working on healthcare systems"},
            {q: "Experience with financial systems"},
            {q: "Working on gaming applications"},
            {q: "Experience with embedded systems"},
            {q: "Working on IoT projects"},
            {q: "Experience with blockchain technology"},
            {q: "Working on AR/VR applications"},
            {q: "Experience with quantum computing"},
            {q: "Working on open source projects"},
            {q: "Experience with research projects"},
            {q: "Working on government contracts"},
            {q: "Experience with education technology"},
            {q: "Working on social media platforms"}
        ],
        "Challenges": [
            {q: "Biggest professional challenge"},
            {q: "How handle work pressure?"},
            {q: "Dealing with failure in project"},
            {q: "Handling ambiguous requirements"},
            {q: "Learning from mistakes"},
            {q: "Adapting to change"},
            {q: "Managing multiple projects"},
            {q: "Technical challenge overcome"},
            {q: "Working with limited resources"},
            {q: "Handling difficult client"},
            {q: "Dealing with imposter syndrome"},
            {q: "Handling technology obsolescence"},
            {q: "Managing technical debt"},
            {q: "Handling production incidents"},
            {q: "Dealing with scope creep"},
            {q: "Handling team turnover"},
            {q: "Managing stakeholder expectations"},
            {q: "Handling budget cuts"},
            {q: "Dealing with legacy code"},
            {q: "Handling security breaches"},
            {q: "Managing performance issues"},
            {q: "Handling data migration"},
            {q: "Dealing with third-party dependencies"},
            {q: "Handling compliance requirements"},
            {q: "Managing technical interviews"},
            {q: "Handling code reviews"},
            {q: "Dealing with architecture changes"},
            {q: "Handling deployment failures"},
            {q: "Managing on-call rotations"},
            {q: "Handling customer escalations"},
            {q: "Dealing with vendor management"},
            {q: "Handling patent applications"},
            {q: "Managing open source contributions"},
            {q: "Handling accessibility requirements"},
            {q: "Dealing with international regulations"},
            {q: "Handling data privacy requirements"},
            {q: "Managing team across time zones"},
            {q: "Handling cultural differences"},
            {q: "Dealing with organizational politics"},
            {q: "Handling merger/acquisition transition"}
        ],
        "Goals": [
            {q: "Where see yourself in 5 years?"},
            {q: "Short-term career goals"},
            {q: "Long-term career aspirations"},
            {q: "Why interested in this role?"},
            {q: "What motivates you?"},
            {q: "Professional development goals"},
            {q: "Skills want to develop"},
            {q: "Why leave current job?"},
            {q: "What looking for in company?"},
            {q: "Expectations from this role"},
            {q: "Career transition goals"},
            {q: "Technical skills development plan"},
            {q: "Leadership goals"},
            {q: "Management aspirations"},
            {q: "Entrepreneurial goals"},
            {q: "Research interests"},
            {q: "Open source contributions goals"},
            {q: "Conference speaking goals"},
            {q: "Publication goals"},
            {q: "Mentoring goals"},
            {q: "Community involvement goals"},
            {q: "Work-life balance goals"},
            {q: "Remote work preferences"},
            {q: "Team size preferences"},
            {q: "Company culture preferences"},
            {q: "Industry focus goals"},
            {q: "Technology stack preferences"},
            {q: "Compensation expectations"},
            {q: "Growth trajectory expectations"},
            {q: "Learning and development expectations"},
            {q: "Impact goals"},
            {q: "Innovation goals"},
            {q: "Scale goals"},
            {q: "International experience goals"},
            {q: "Diversity and inclusion goals"},
            {q: "Sustainability goals"},
            {q: "Ethical technology goals"},
            {q: "Accessibility goals"},
            {q: "Security goals"},
            {q: "Performance goals"}
        ],
        "Strengths/Weaknesses": [
            {q: "Biggest strength and examples"},
            {q: "Biggest weakness and improvement"},
            {q: "Technical strengths"},
            {q: "Areas for improvement"},
            {q: "How handle criticism?"},
            {q: "What makes you unique?"},
            {q: "Receive feedback on weakness"},
            {q: "Soft skills strengths"},
            {q: "Overcoming weaknesses"},
            {q: "Balance multiple strengths"},
            {q: "Problem-solving strengths"},
            {q: "Communication strengths"},
            {q: "Leadership strengths"},
            {q: "Teamwork strengths"},
            {q: "Technical depth vs breadth"},
            {q: "Adaptability strength"},
            {q: "Creativity strength"},
            {q: "Analytical strengths"},
            {q: "Time management strengths"},
            {q: "Delegation strengths"},
            {q: "Mentoring strengths"},
            {q: "Learning agility strength"},
            {q: "Resilience strength"},
            {q: "Innovation strength"},
            {q: "Strategic thinking strength"},
            {q: "Execution strength"},
            {q: "Quality focus strength"},
            {q: "Customer focus strength"},
            {q: "Technical debt management"},
            {q: "Code quality focus"},
            {q: "Testing strengths"},
            {q: "Debugging strengths"},
            {q: "Performance optimization"},
            {q: "Security awareness"},
            {q: "Documentation skills"},
            {q: "Code review skills"},
            {q: "System design skills"},
            {q: "Architecture skills"},
            {q: "Troubleshooting skills"},
            {q: "Incident management skills"}
        ]
    }
};